"use client";

import { ReactNode, useState } from "react";
import { DetailTab, SalesProject, submissionTimingLabel } from "./demo-data";

type OpenProject = (id: string, tab?: DetailTab, context?: { source: string; title: string; summary: string; activityId?: string }) => void;
type Tone = "danger" | "warning" | "success" | "info" | "neutral";

function money(value: number) { return `${value.toLocaleString("zh-CN")} 万`; }
function score(project: SalesProject) { return Math.round((project.health.relationship + project.health.resource + project.health.operation) / 3); }
function toneOf(value: string): Tone {
  if (/高|重大|逾期|阻断|缺失|拒绝|重新评审|未批准/.test(value)) return "danger";
  if (/中|待|进行|关注|例外/.test(value)) return "warning";
  if (/完成|批准|健康|接收|低风险|中标/.test(value)) return "success";
  if (/只读|外部|当前/.test(value)) return "info";
  return "neutral";
}
function Tag({ children, tone }: { children: ReactNode; tone?: Tone }) { const text = String(children); return <span className={`ops-tag ${tone ?? toneOf(text)}`}><i />{children}</span>; }
function PageHead({ kicker, title, description, children }: { kicker: string; title: string; description: string; children?: ReactNode }) {
  return <header className="ops-page-head"><div><span>{kicker}</span><h1>{title}</h1><p>{description}</p></div>{children && <div>{children}</div>}</header>;
}
function ProjectIdentity({ project }: { project: SalesProject }) { return <div className="ops-project-id"><strong>{project.name}</strong><small>{project.id} · {project.owner} · {project.stage} {project.stageName}</small></div>; }

type DecisionKind = "立项审批" | "阶段门" | "偏差审批" | "定价例外" | "结果确认";
type DecisionItem = { id: string; project: SalesProject; kind: DecisionKind; title: string; fact: string; impact: string; applicant: string; due: string; tab: DetailTab; quick?: boolean };

export function DecisionCenter({ projects, realPendingGates, onOpenProject, onNotify }: { projects: SalesProject[]; realPendingGates: Record<string, "G1" | "G2" | "G3" | "G4" | "G5" | "G6">; onOpenProject: OpenProject; onNotify: (message: string) => void }) {
  const realPending = new Set(Object.keys(realPendingGates));
  const persistedDecisions: DecisionItem[] = projects.filter(project => realPending.has(project.id)).map(project => {
    const code = realPendingGates[project.id];
    return {
      id: `${code}-${project.id}`, project, kind: code === "G1" ? "立项审批" : "阶段门",
      title: code === "G1" ? `${project.customer}${project.target}立项审批` : code === "G2" ? `${project.name} G2投入启动门` : code === "G3" ? `${project.name} G3需求与技术基线门` : code === "G4" ? `${project.name} G4核价授权门` : code === "G5" ? `${project.name} G5商务决策与提交门` : `${project.name} G6结果与移交门`,
      fact: code === "G1" ? `采购意向证据“${project.evidence}”已写入D1，客户、标的、金额与Owner等待G1决策。` : code === "G2" ? "首版赢单策略、客户经营、资源投入、投报计划和专业启动评估已形成不可变快照，等待主管明确投入范围、优先级和期限。" : code === "G3" ? "需求与技术来源快照已冻结，等待独立技术评审人确认；技术负责人、销售Owner和销售主管均不能代批。" : code === "G4" ? "核价专业来源快照已冻结，等待财务/价格授权人确认；销售主管只可查看与督办。" : code === "G5" ? "G4价格授权、投标专员形成的提交包及专业评审人的独立结论已冻结，等待主管作一次投/不投及提交授权决策。" : "L2.9正式结果事实及中标基线血缘或未成交复盘已冻结，等待主管一次G6确认。",
      impact: code === "G1" ? "批准后项目进入S1立项与策略；退回则保持S0并要求Owner补充事实与证据。" : code === "G2" ? "批准后项目进入S2需求与方案；退回则保持S1并要求Owner补充双轨事实。" : code === "G3" ? "技术确认后才可进入S3核价评审；销售主管无权代批。" : code === "G4" ? "财务/价格授权后才可进入S4定价与投标；销售主管无权代批。" : code === "G5" ? "批准投标后项目仍在S4，投标作业回传有效提交回执才进入S5；不投则直接进入S5且不伪造提交。" : "赢单批准后等待合同APP接收再进S6；未成交批准后在结构化复盘完整的前提下Closed。",
      applicant: project.owner, due: "待处理", tab: "gate",
    };
  });
  const decisions: DecisionItem[] = persistedDecisions;
  const filters = ["全部待处理", "立项审批", "阶段门", "偏差审批", "定价例外", "结果确认"] as const;
  const [filter, setFilter] = useState<(typeof filters)[number]>("全部待处理");
  const visible = decisions.filter(item => filter === "全部待处理" || item.kind === filter);
  const [selectedId, setSelectedId] = useState(decisions[0]?.id ?? "");
  const selected = visible.find(item => item.id === selectedId) ?? visible[0] ?? decisions[0];
  const selectedGateCode = selected ? realPendingGates[selected.project.id] : undefined;
  return <div className="ops-page">
    <PageHead kicker="STAGE GATE" title="阶段门中心" description="只展示D1中真实存在的待处理Gate；资源、专业确认和外部任务不伪装成主管审批。"><Tag tone={decisions.length ? "danger" : "success"}>{decisions.length}项待处理</Tag></PageHead>
    <section className="ops-kpi-strip compact"><article><span>待处理Gate</span><strong>{decisions.length}</strong><small>按Gate实例ID去重</small></article><article><span>立项审批</span><strong>{decisions.filter(item => item.kind === "立项审批").length}</strong><small>G1真实实例</small></article><article><span>专业Gate督办</span><strong>{decisions.filter(item => ["G3", "G4"].includes(realPendingGates[item.project.id])).length}</strong><small>主管只能查看和督办</small></article><article><span>业务Gate决策</span><strong>{decisions.filter(item => !["G1", "G3", "G4"].includes(realPendingGates[item.project.id])).length}</strong><small>进入项目上下文处理</small></article></section>
    <nav className="ops-filter-tabs">{filters.map(item => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}<b>{item === "全部待处理" ? decisions.length : decisions.filter(decision => decision.kind === item).length}</b></button>)}</nav>
    <div className="ops-master-detail">
      <section className="ops-card-list"><header><div><strong>{filter}</strong><small>按时限、交标影响和审批层级排序</small></div><button onClick={() => onNotify("当前列表可按真实Gate类型筛选")}>筛选</button></header>{visible.map(item => <button className={selected?.id === item.id ? "active" : ""} key={item.id} onClick={() => setSelectedId(item.id)}><Tag>{item.due}</Tag><ProjectIdentity project={item.project} /><strong>{item.title}</strong><p>{item.fact}</p><footer><span>{item.kind} · 申请人 {item.applicant}</span><b>审查 ›</b></footer></button>)}{visible.length === 0 && <div className="ops-empty"><strong>当前分类没有真实待处理事项</strong><p>系统不会用静态审批填充队列。</p></div>}</section>
      {selected ? <aside className="ops-focus-panel"><header><div><span>当前阶段门事项</span><h2>{selected.title}</h2></div><Tag>{selected.due}</Tag></header><ProjectIdentity project={selected.project} /><div className="ops-fact-block"><span>已确认事实</span><p>{selected.fact}</p></div><div className="ops-impact-block"><span>决策影响</span><p>{selected.impact}</p></div><div className="ops-ai-brief"><i>AI</i><div><strong>辅助建议</strong><p>该事项会改变阶段、授权或结果状态，建议进入完整业务上下文后决策。</p><small>AI不自动批准，最终责任属于审批人。</small></div></div><dl className="ops-meta"><div><dt>申请人</dt><dd>{selected.applicant}</dd></div><div><dt>审批类型</dt><dd>{selected.kind}</dd></div><div><dt>当前阶段</dt><dd>{selected.project.stage} {selected.project.stageName}</dd></div><div><dt>预计金额</dt><dd>{money(selected.project.amount)}</dd></div></dl><footer><button onClick={() => onOpenProject(selected.project.id, "gate", { source: "阶段门中心", title: selected.title, summary: selectedGateCode === "G3" || selectedGateCode === "G4" ? "主管可查看并督办指定专业责任人，不可代替专业确认" : "请在完整业务上下文中形成真实阶段门结论" })}>{selectedGateCode === "G3" || selectedGateCode === "G4" ? "查看并督办" : "查看退回条件"}</button><button className="primary" onClick={() => onOpenProject(selected.project.id, selected.tab, { source: "阶段门中心", title: selected.title, summary: selected.fact })}>进入完整处理</button></footer></aside> : <aside className="ops-focus-panel"><div className="ops-empty"><strong>没有真实待处理Gate</strong><p>这里不会再生成静态审批事项。</p></div></aside>}
    </div>
  </div>;
}

export function SalesActionCenter({ projects, onOpenProject, onNotify }: { projects: SalesProject[]; onOpenProject: OpenProject; onNotify: (message: string) => void }) {
  const mine = projects.filter(project => project.owner === "陈晨" || project.participants?.includes("陈晨"));
  const tabFor = (code: string): DetailTab => code === "ACT-SPM-02" ? "strategy" : code === "ACT-SPM-03" ? "relations" : code === "ACT-SPM-04" ? "resources" : "actions";
  const items = mine.flatMap(project => [
    ...(project.activityRecords ?? []).filter(activity => !["completed", "cancelled"].includes(activity.status)).map(activity => ({ id: activity.id, activityId: activity.id, project, group: activity.readOnly ? "等待客户/外部" : activity.ownerName === "陈晨" ? activity.timelinessStatus === "overdue" ? "已逾期" : "我现在要做" : "等待内部", title: activity.title, reason: activity.purpose, owner: activity.ownerName, due: activity.plannedEnd, tab: tabFor(activity.definitionCode), evidence: activity.evidenceRefs.join("；") || "完成证据待形成", allowed: activity.readOnly ? "只读查看外部状态；可催办，不可代办" : activity.definitionCode === "ACT-SPM-04" ? "查看资源需求或进行允许的资源操作" : "进入来源页面补充事实，或更新该活动状态与证据" })),
    ...project.versions.filter(version => version.status === "需要重新评审").map(version => ({ id: version.id, activityId: undefined, project, group: "版本异常", title: `${version.kind} ${version.id}需要重新评审`, reason: version.summary, owner: version.creator, due: "待处理", tab: "versions" as DetailTab, evidence: version.basedOn, allowed: "查看版本来源和变更影响；由权威责任人完成重新评审" })),
  ]);
  const filters = ["我现在要做", "等待内部", "等待客户/外部", "已逾期", "版本异常"];
  const [filter, setFilter] = useState("我现在要做");
  const all = items;
  const visible = all.filter(item => item.group === filter);
  const [selectedId, setSelectedId] = useState(all[0]?.id ?? "");
  const selected = visible.find(item => item.id === selectedId) ?? visible[0];
  return <div className="ops-page"><PageHead kicker="MY WORK" title="行动中心" description="只显示真实活动、外部等待和版本异常；行动必须从具体业务缺口发起，不在工作台泛化新增。" /><nav className="ops-filter-tabs">{filters.map(item => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}<b>{all.filter(action => action.group === item).length}</b></button>)}</nav><div className="ops-master-detail sales"><section className="ops-card-list"><header><div><strong>{filter}</strong><small>按责任归属、时间状态和权威系统分类</small></div></header>{visible.map(item => <button className={selected?.id === item.id ? "active" : ""} key={item.id} onClick={() => setSelectedId(item.id)}><Tag>{item.due}</Tag><ProjectIdentity project={item.project} /><strong>{item.title}</strong><p>{item.reason}</p><footer><span>责任/等待：{item.owner}</span><b>{item.group.startsWith("等待") ? "查看 ›" : "处理 ›"}</b></footer></button>)}{visible.length === 0 && <div className="ops-empty"><strong>当前分类没有真实事项</strong><p>系统不会用静态任务填充空队列。</p></div>}</section>{selected && <aside className="ops-focus-panel"><header><div><span>当前业务任务</span><h2>{selected.title}</h2></div><Tag>{selected.group}</Tag></header><ProjectIdentity project={selected.project} /><div className="ops-fact-block"><span>为什么现在要做</span><p>{selected.reason}</p></div><div className="ops-impact-block"><span>允许操作</span><p>{selected.allowed}</p></div><div className="ops-impact-block"><span>完成证据</span><p>{selected.evidence}</p></div><footer>{selected.group.startsWith("等待") && <button onClick={() => onNotify(`已生成给${selected.owner}的催办草稿，发送前需人工确认`)}>生成催办</button>}<button className="primary" onClick={() => onOpenProject(selected.project.id, selected.tab, { source: "销售行动中心", title: selected.title, summary: selected.reason, activityId: selected.activityId })}>{selected.group.startsWith("等待") ? "查看来源状态" : "进入具体工作"}</button></footer></aside>}</div></div>;
}

export function ResourceCenter({ projects, onOpenProject, onNotify }: { projects: SalesProject[]; onOpenProject: OpenProject; onNotify: (message: string) => void }) {
  const pools = [
    { id: "technical", name: "技术与方案", total: 8, average: 84, available: 1, demand: 3, tone: "danger", members: [{ name: "赵工", skill: "主变方案 / 技术评审", load: 92, projects: 4, available: "8月23日" }, { name: "钱工", skill: "配变与能效", load: 76, projects: 3, available: "可投入20%" }, { name: "黄工", skill: "箱变与成套", load: 68, projects: 2, available: "可投入30%" }] },
    { id: "costing", name: "核价与定价", total: 6, average: 89, available: 1, demand: 4, tone: "danger", members: [{ name: "罗总", skill: "价格授权L2", load: 94, projects: 5, available: "仅审批投入" }, { name: "王倩", skill: "成本测算 / 风险储备", load: 82, projects: 4, available: "8月21日" }, { name: "陈伟", skill: "采购询价 / 物流成本", load: 73, projects: 3, available: "可投入20%" }] },
    { id: "sales", name: "销售Owner", total: 12, average: 71, available: 3, demand: 2, tone: "warning", members: [{ name: "陈晨", skill: "电网客户 / 复杂项目", load: 78, projects: 4, available: "可投入15%" }, { name: "林涛", skill: "新能源 / 投标推进", load: 86, projects: 3, available: "8月20日" }, { name: "孙倩", skill: "存量增购 / 数字化", load: 62, projects: 2, available: "可投入30%" }] },
    { id: "commercial", name: "商务投标协同", total: 7, average: 74, available: 2, demand: 3, tone: "warning", members: [{ name: "郭专员", skill: "投标协同 / 提交回执", load: 88, projects: 5, available: "8月22日" }, { name: "林专员", skill: "商务条款 / 报价协同", load: 72, projects: 3, available: "可投入20%" }, { name: "何敏", skill: "渠道报价 / 资质", load: 60, projects: 2, available: "可投入35%" }] },
    { id: "executive", name: "高层伙伴", total: 5, average: 64, available: 2, demand: 4, tone: "success", members: [{ name: "刘总", skill: "电网与能源高层关系", load: 72, projects: 4, available: "可协调1项" }, { name: "王总", skill: "海外EPC / 渠道关系", load: 58, projects: 2, available: "可协调2项" }, { name: "周总", skill: "轨交与重大项目", load: 61, projects: 3, available: "可协调1项" }] },
  ] as const;
  const [selectedPool, setSelectedPool] = useState(pools[0].id as string);
  const pool = pools.find(item => item.id === selectedPool) ?? pools[0];
  const needs = projects.flatMap(project => project.resources.filter(resource => resource.required && resource.status !== "已到位").map(resource => ({ project, resource })));
  return <div className="ops-page"><PageHead kicker="CAPACITY & ASSIGNMENT" title="资源与角色" description="先看各类人员供给和负荷，再匹配具体项目需求；指派后本人接受责任才算到位。"><Tag tone="danger">{needs.length}项待配置</Tag></PageHead>
    <div className="ops-section-title"><div><span>RESOURCE POOLS</span><h2>团队能力与负荷全景</h2></div><small>数据源：资源能力中心｜只读模拟</small></div>
    <section className="ops-pool-grid">{pools.map(item => <button key={item.id} className={`${item.id === selectedPool ? "active" : ""} ${item.tone}`} onClick={() => setSelectedPool(item.id)}><header><strong>{item.name}</strong><span>{item.total}人</span></header><div><b>{item.average}%</b><span>平均负荷</span></div><i><em style={{ width: `${item.average}%` }} /></i><footer><span>可用 {item.available}人</span><span>新增需求 {item.demand}</span></footer></button>)}</section>
    <section className="ops-pool-detail"><header><div><span>SELECTED POOL</span><h2>{pool.name}人员负荷</h2></div><Tag tone={pool.average >= 85 ? "danger" : pool.average >= 70 ? "warning" : "success"}>{pool.average >= 85 ? "容量紧张" : pool.average >= 70 ? "需要关注" : "存在余量"}</Tag></header><div>{pool.members.map(member => <article key={member.name} className={member.load >= 85 ? "overload" : ""}><header><strong>{member.name}</strong><span>{member.projects}个在管项目</span></header><p>{member.skill}</p><div className="ops-member-load"><span>当前负荷</span><b>{member.load}%</b><i><em style={{ width: `${member.load}%` }} /></i></div><footer><span>可投入：{member.available}</span><button onClick={() => onNotify(`已选择${member.name}作为候选；提交前仍需检查项目冲突并由本人接受责任`)}>设为候选</button></footer></article>)}</div></section>
    <div className="ops-section-title"><div><span>PROJECT DEMAND</span><h2>当前项目资源需求</h2></div><small>按交标时限和角色必要性排序</small></div><div className="ops-resource-grid">{needs.map(({ project, resource }) => <article className={resource.status === "缺失" ? "critical" : (resource.load ?? 0) >= 85 ? "attention" : ""} key={`${project.id}-${resource.id}`}><header><Tag>{resource.status}</Tag><span>{submissionTimingLabel(project)}</span></header><ProjectIdentity project={project} /><h3>{resource.role}</h3><div className="ops-capability-tags">{resource.capabilities?.map(item => <b key={item}>{item}</b>)}</div><div className="ops-load"><span>当前候选：{resource.person}</span><strong>{resource.person === "待指派" ? "待匹配" : `${resource.load ?? 0}%`}</strong><i><em style={{ width: `${resource.load ?? 0}%` }} /></i><small>{resource.activeProjects ?? 0}个在管项目 · {resource.availableFrom}</small></div><footer><button onClick={() => onOpenProject(project.id, "resources", { source: "资源与角色", title: `${resource.role}资源协调`, summary: `${resource.person} · 当前负荷${resource.load ?? 0}%` })}>查看项目依据</button><button className="primary" onClick={() => onNotify(`已生成${resource.role}资源协调任务；仍需候选人接受责任`)}>发起协调</button></footer></article>)}</div>
  </div>;
}

export function RiskCenter({ projects, onOpenProject, onNotify }: { projects: SalesProject[]; onOpenProject: OpenProject; onNotify: (message: string) => void }) {
  const risks = projects.flatMap(project => project.risks.filter(risk => risk.status !== "已关闭").map(risk => ({ project, risk }))).sort((a, b) => (a.risk.level === "重大" ? -1 : a.risk.level === "高" ? -1 : 1) - (b.risk.level === "重大" ? -1 : b.risk.level === "高" ? -1 : 1));
  const [selectedId, setSelectedId] = useState(risks[0]?.risk.id ?? "");
  const selected = risks.find(item => item.risk.id === selectedId) ?? risks[0];
  return <div className="ops-page"><PageHead kicker="RISK INTERVENTION" title="风险与行动" description="主管关注的不是风险数量，而是哪些风险需要跨项目协调、升级或补充关闭证据。"><Tag tone="danger">{risks.filter(item => item.risk.level === "高" || item.risk.level === "重大").length}项高风险</Tag></PageHead><section className="ops-risk-hero"><div><span>本周管理焦点</span><strong>技术资源与客户关系覆盖是主要风险来源</strong><p>优先处理7日内交标项目的硬阻断，再处理一般性行动延期。</p></div><div><b>{risks.length}</b><span>开放风险</span></div><div><b>{risks.filter(item => item.project.countdown >= 0 && item.project.countdown <= 7).length}</b><span>交标红区</span></div></section><div className="ops-master-detail"><section className="ops-card-list risk"><header><div><strong>风险优先队列</strong><small>每条风险必须关联行动、责任人和关闭证据</small></div></header>{risks.map(({ project, risk }) => <button className={selected?.risk.id === risk.id ? "active" : ""} key={`${project.id}-${risk.id}`} onClick={() => setSelectedId(risk.id)}><Tag>{risk.level}风险</Tag><ProjectIdentity project={project} /><strong>{risk.title}</strong><p>{risk.category} · 当前状态：{risk.status}</p><footer><span>{risk.owner} · {risk.due}</span><b>查看处置 ›</b></footer></button>)}</section>{selected && <aside className="ops-focus-panel"><header><div><span>风险事实</span><h2>{selected.risk.title}</h2></div><Tag>{selected.risk.level}风险</Tag></header><ProjectIdentity project={selected.project} /><div className="ops-fact-block"><span>当前证据</span><p>{selected.risk.evidence}</p></div><div className="ops-impact-block"><span>主管介入点</span><p>{selected.project.resources.some(item => item.required && item.status !== "已到位") ? "协调关键资源并确认本人接受责任。" : "检查计划动作、截止时间和关闭证据是否足够。"}</p></div><dl className="ops-meta"><div><dt>风险Owner</dt><dd>{selected.risk.owner}</dd></div><div><dt>截止时间</dt><dd>{selected.risk.due}</dd></div><div><dt>项目倒计时</dt><dd>{selected.project.countdown}天</dd></div><div><dt>项目健康度</dt><dd>{score(selected.project)}分</dd></div></dl><footer><button onClick={() => onNotify(`已生成给${selected.risk.owner}的督办草稿，尚未下发`)}>生成督办</button><button className="primary" onClick={() => onOpenProject(selected.project.id, "actions", { source: "风险与行动", title: selected.risk.title, summary: selected.risk.evidence })}>进入处置闭环</button></footer></aside>}</div></div>;
}

export function ConfigurationCenter({ projects, onOpenProject }: { projects: SalesProject[]; onOpenProject: OpenProject }) {
  const issues = projects.flatMap(project => [
    ...project.versions.filter(version => version.status === "需要重新评审").map(version => ({ id: version.id, project, type: "版本重评", title: `${version.kind} ${version.id}`, fact: version.summary, status: version.status, tab: "versions" as DetailTab })),
    ...project.deviations.filter(deviation => deviation.status === "待审批").map(deviation => ({ id: deviation.id, project, type: "未批准偏差", title: `${deviation.field}偏差 ${deviation.id}`, fact: `${deviation.requirement} → ${deviation.proposal}`, status: deviation.status, tab: "versions" as DetailTab })),
    ...project.resources.filter(resource => resource.required && resource.status === "缺失").map(resource => ({ id: `RES-${resource.id}`, project, type: "提交阻断", title: `${resource.role}缺失`, fact: "必需资源未到位将阻止正式提交或阶段推进。", status: "阻断", tab: "resources" as DetailTab })),
  ]);
  const [selectedId, setSelectedId] = useState(issues[0]?.id ?? ""); const selected = issues.find(item => item.id === selectedId) ?? issues[0];
  return <div className="ops-page"><PageHead kicker="CONFIGURATION GOVERNANCE" title="版本与配置" description="只聚焦跨项目异常：需求变更、重新评审、未批准偏差和正式提交阻断。"><Tag tone="danger">{issues.length}项异常</Tag></PageHead><section className="ops-config-summary"><article className="danger"><b>{projects.reduce((sum, project) => sum + project.versions.filter(item => item.status === "需要重新评审").length, 0)}</b><span>待重新评审版本</span><small>需求变更已传播至下游</small></article><article className="warning"><b>{projects.reduce((sum, project) => sum + project.deviations.filter(item => item.status === "待审批").length, 0)}</b><span>未批准偏差</span><small>差异必须评估、审批、追溯</small></article><article><b>{projects.filter(project => project.externalBid.status === "已提交").length}</b><span>正式提交锁定</span><small>已提交版本不可覆盖</small></article></section><div className="ops-master-detail"><section className="ops-card-list config"><header><div><strong>配置异常队列</strong><small>按正式提交影响和变更传播范围排序</small></div></header>{issues.map(item => <button className={selected?.id === item.id ? "active" : ""} key={`${item.project.id}-${item.id}`} onClick={() => setSelectedId(item.id)}><Tag>{item.type}</Tag><ProjectIdentity project={item.project} /><strong>{item.title}</strong><p>{item.fact}</p><footer><span>{item.status}</span><b>检查影响 ›</b></footer></button>)}</section>{selected && <aside className="ops-focus-panel"><header><div><span>异常影响</span><h2>{selected.title}</h2></div><Tag>{selected.status}</Tag></header><ProjectIdentity project={selected.project} /><div className="ops-trace-mini"><div><span>客户需求</span><b>→</b><span>技术方案</span><b>→</b><span>核价方案</span><b>→</b><span>投标方案</span></div><small>红色节点表示需要重新评审，正式提交版本保持锁定。</small></div><div className="ops-fact-block"><span>已确认事实</span><p>{selected.fact}</p></div><div className="ops-impact-block"><span>控制要求</span><p>识别差异、评估影响、获得批准并保留上下游追溯；不能覆盖已批准或正式提交版本。</p></div><footer><button className="primary" onClick={() => onOpenProject(selected.project.id, selected.tab, { source: "版本与配置", title: selected.title, summary: selected.fact })}>进入配置处理</button></footer></aside>}</div></div>;
}

export function ReviewCenter({ projects, onOpenProject, onNotify }: { projects: SalesProject[]; onOpenProject: OpenProject; onNotify: (message: string) => void }) {
  const resultProjects = projects.filter(project => project.stage === "S5" || project.stage === "S6" || project.result !== "pending");
  const pending = resultProjects.filter(project => project.result === "pending"); const won = resultProjects.filter(project => project.result === "won"); const lost = resultProjects.filter(project => project.result === "lost");
  return <div className="ops-page"><PageHead kicker="RESULT & LEARNING" title="结果与复盘" description="正式结果、移交和复盘集中管理；合同、订单和交付继续保持外部系统只读。"><Tag tone="warning">{pending.length}项待确认</Tag></PageHead><section className="ops-result-flow"><article><i>1</i><div><span>待确认结果</span><strong>{pending.length}</strong><small>核验客户正式通知</small></div></article><b>→</b><article className="won"><i>2A</i><div><span>中标与移交</span><strong>{won.length}</strong><small>生成不可覆盖基线</small></div></article><article className="lost"><i>2B</i><div><span>丢标与复盘</span><strong>{lost.length}</strong><small>形成结构化改进行动</small></div></article></section><div className="ops-result-grid"><section><header><div><span>PENDING</span><h2>等待正式结果</h2></div></header>{pending.map(project => <article key={project.id}><ProjectIdentity project={project} /><p>{project.externalBid.receipt === "—" ? "尚未取得客户正式结果通知。" : `已固化客户回执：${project.externalBid.receipt}`}</p><footer><Tag>{project.externalBid.status}</Tag><button onClick={() => onOpenProject(project.id, "result", { source: "结果与复盘", title: "正式结果确认", summary: "核验客户结果证据并选择中标或丢标分支" })}>核验结果 ›</button></footer></article>)}</section><section><header><div><span>TRANSFER</span><h2>中标移交</h2></div></header>{won.map(project => <article key={project.id}><ProjectIdentity project={project} /><p>中标基线：{project.baseline?.id ?? "待生成"}</p><footer><Tag>{project.baseline?.transferStatus ?? "待移交"}</Tag><button onClick={() => onOpenProject(project.id, "result")}>查看只读移交 ›</button></footer></article>)}{won.length === 0 && <div className="ops-empty"><strong>暂无已确认中标项目</strong></div>}</section><section><header><div><span>REVIEW</span><h2>丢标复盘</h2></div></header>{lost.map(project => <article key={project.id}><ProjectIdentity project={project} /><p>{project.lostReview?.reason ?? "等待结构化复盘"}</p><footer><Tag tone="neutral">已复盘</Tag><button onClick={() => onOpenProject(project.id, "result")}>查看改进行动 ›</button></footer></article>)}{lost.length === 0 && <div className="ops-empty"><strong>暂无已确认丢标项目</strong><p>可在结果项目中回放丢标分支。</p><button onClick={() => onNotify("请从待确认结果进入具体项目填写结构化复盘")}>查看规则</button></div>}</section></div></div>;
}
